//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "caption")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub auto_cap_id: i32,
    pub ext: Option<String>,
    pub protocol: Option<String>,
    pub url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::automaticcaptions::Entity",
        from = "Column::AutoCapId",
        to = "super::automaticcaptions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Automaticcaptions,
}

impl Related<super::automaticcaptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Automaticcaptions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
