//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod automaticcaptions;
pub mod caption;
pub mod channelcategory;
pub mod channeltag;
pub mod channelthumbnail;
pub mod chapter;
pub mod entry;
pub mod format;
pub mod formatsortfield;
pub mod fragment;
pub mod heatmap;
pub mod httpheader;
pub mod payload;
pub mod requesteddownload;
pub mod subtitle;
pub mod subtitletype;
pub mod version;
pub mod videocategory;
pub mod videotag;
pub mod videothumbnail;
