//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::automaticcaptions::Entity as Automaticcaptions;
pub use super::caption::Entity as Caption;
pub use super::channelcategory::Entity as Channelcategory;
pub use super::channeltag::Entity as Channeltag;
pub use super::channelthumbnail::Entity as Channelthumbnail;
pub use super::chapter::Entity as Chapter;
pub use super::entry::Entity as Entry;
pub use super::format::Entity as Format;
pub use super::formatsortfield::Entity as Formatsortfield;
pub use super::fragment::Entity as Fragment;
pub use super::heatmap::Entity as Heatmap;
pub use super::httpheader::Entity as Httpheader;
pub use super::payload::Entity as Payload;
pub use super::requesteddownload::Entity as Requesteddownload;
pub use super::subtitle::Entity as Subtitle;
pub use super::subtitletype::Entity as Subtitletype;
pub use super::version::Entity as Version;
pub use super::videocategory::Entity as Videocategory;
pub use super::videotag::Entity as Videotag;
pub use super::videothumbnail::Entity as Videothumbnail;
