//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "requesteddownload")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub write_download_archive: Option<i32>,
    pub filename: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub abr: Option<f64>,
    pub acodec: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub aspect_ratio: Option<f64>,
    pub audio_ext: Option<String>,
    pub columns: Option<i32>,
    pub ext: Option<String>,
    pub filesize_approx: Option<i32>,
    pub format: Option<String>,
    pub format_id: String,
    pub format_note: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub fps: Option<f64>,
    pub height: Option<i32>,
    pub protocol: Option<String>,
    pub resolution: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub tbr: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub vbr: Option<f64>,
    pub vcodec: Option<String>,
    pub width: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
